### ISSUE TITLE
你好请问一下可以自定义java模板和mapper模板吗

### ISSUE THREAD

**Issue by hackedbyxx** [moztl/Free-Mybatis-Tool#10]
需要自己定制化一下

**Comment by moztl** [comment]
感谢反馈，这个暂时不支持。

**Comment by hackedbyxx** [comment]
好吧，希望后续可以支持一下

**Comment by moztl** [comment]
是需要很复杂的定制化么？正常的情况下，可以通过 Options 中的不同功能的选择，组建想要的模版格式。后期也是在 Options 中增加更多的功能，来实现定制化模板。

**Comment by hackedbyxx** [comment]
也不是很复杂就是想加点mybatis plus的集成

**Comment by moztl** [comment]
这个之前有打算增加过这个功能，后来搁置了。后面我看看有时间我加一下。

**Comment by hackedbyxx** [comment]
好的，有机会再加，谢谢
