### ISSUE TITLE
The property tag in the xml file is red

### ISSUE THREAD

**Issue by c1994426** [moztl/Free-Mybatis-Tool#11]
Mybatis has configured the default scanning path of the class in application.yml, but Free MyBatis Tool can't read it, which leads to the red value of the property tag in the xml file. What is the solution? (have get and set)

**Comment by moztl** [comment]
Check if the namespace configuration is correct in xml






------------------ Original ------------------
From: c1994426 ***@***.***&gt;
Date: Thu,May 16,2024 6:35 AM
To: moztl/Free-Mybatis-Tool ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [moztl/Free-Mybatis-Tool] The property tag in the xml file is red(Issue #11)





 
Mybatis has configured the default scanning path of the class in application.yml, but Free MyBatis Tool can't read it, which leads to the red value of the property tag in the xml file. What is the solution? (have get and set)
