### ISSUE TITLE
点击入参变量无法跳转到对应的定义处

### ISSUE THREAD

**Issue by crMEI** [moztl/Free-Mybatis-Tool#15]
插件版本2.2.2，idea版本2023.3.7，操作系统macOs,点击入参变量无法跳转到对应的定义处
![image](https://github.com/moztl/Free-Mybatis-Tool/assets/21358014/13c5aa3e-06db-4633-b299-fe3abeefcb71)

**Comment by moztl** [comment]
感谢反馈，插件本身就没有这个功能，可以点击上方的 resultType。
