### ISSUE TITLE
亲，新版本插件不支持了呦

### ISSUE THREAD

**Issue by qq253498229** [moztl/Free-Mybatis-Tool#3]

**Comment by moztl** [comment]
感谢反馈，将会在新版本 v2.1.0 兼容 IDEA2022.1

**Comment by moztl** [comment]
# Releases 已更新 v2.1.0
# IDEA Marketplace 已提交审核

**Comment by hellorayza** [comment]
Not compatible with the version of your running IDE (IntelliJ IDEA 2024.3.3)

**Comment by moztl** [comment]
感谢反馈，支持的哦！

**Comment by hellorayza** [comment]
Oh,Sorry! My IntelliJ  IDEA is the community edition.

**Comment by moztl** [comment]
Yes, you need IU

<img width="711" alt="Image" src="https://github.com/user-attachments/assets/7e155918-36d8-41d0-a64a-3cf45da3bb1f" />
