### ISSUE TITLE
Not compatible with the version of your running IDE (WebStorm 2022.2, IntelliJ IDEA 2022.2)

### ISSUE THREAD

**Issue by jayzch** [moztl/Free-Mybatis-Tool#5]
求升级

**Comment by moztl** [comment]
感谢您的来信：
&nbsp; &nbsp; &nbsp; &nbsp;已提交更新，等待审核。



发自我的iPhone


------------------ Original ------------------
From: Hulk ***@***.***&gt;
Date: Tue,Jul 26,2022 10:32 PM
To: moztl/Free-Mybatis-Tool ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [moztl/Free-Mybatis-Tool] Not compatible with the version of yourrunning IDE (WebStorm 2022.2, IntelliJ IDEA 2022.2) (Issue #5)





 
求升级
