### ISSUE TITLE
map层不显示跳转箭头

### ISSUE THREAD

**Issue by js-yabei** [moztl/Free-Mybatis-Tool#7]
map层不显示跳转箭头咋办？sql文件有指向箭头，map文件没有
![image](https://github.com/moztl/Free-Mybatis-Tool/assets/55583854/9305a52e-86ce-4962-977e-d0606214e707)
![image](https://github.com/moztl/Free-Mybatis-Tool/assets/55583854/b9c55711-0503-4ca3-8979-506fbec5a3e0)

**Comment by moztl** [comment]
感谢反馈，这边本地确认了正常项目Mapper层可以正常显示。
有几个问题需要确认一下：
1.安装的插件版本是哪个版本。
2.IDEA右下角有没有关于本插件的报错信息。
3.Mapper层类那行有没有跳转箭头，或者说是全都没有跳转箭头还是唯独截图中的方法没有跳转箭头。

**Comment by js-yabei** [comment]
感谢回复，问题已经排查出来了，我用mapper.java文件，可以生成sql.xml文件，发现生成的xml文件和mapper文件名称相同，而我现在的sql文件的名称和mapper文件的名称不同，所以没有跳转；需要mapper文件和xml文件名称相同才可以互相跳转；我再研究一下。

**Comment by moztl** [comment]
跳转与 .xml 文件中的 namespace 有关，文件名可以随意变更。希望对你有帮助！

**Comment by js-yabei** [comment]
您好，，但是又发现一个问题，同样的代码，在我的两台电脑打开，一个电脑mapper文件有箭头，另一个就没有，说明只要namespace配了，sql文件名和mapper文件名不一样也可以跳转。这样说明还是哪里有问题，解决不了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月2日(周三) 晚上8:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [moztl/Free-Mybatis-Tool] map层不显示跳转箭头 (Issue #7)




 
跳转与 .xml 文件中的 namespace 有关，文件名可以随意变更。希望对你有帮助！

**Comment by js-yabei** [comment]
解决了，玄学问题，重新拉项目代码到新文件夹打开又好了，感谢回复

**Comment by js-yabei** [comment]
给后来人一个参考，如果出现上述问题可以尝试IDEA 文件-》清除缓存就可以了
