### ISSUE TITLE
关于点击resultMap中collection标签的select属性时无法跳转到对应方法

### ISSUE THREAD

**Issue by Keleisme** [moztl/Free-Mybatis-Tool#8]
我的free mybatis tool版本是2.1.3，在使用resultMap中的collection和association中的select时，ctrl + 左键提示无法跳转
![image](https://github.com/moztl/Free-Mybatis-Tool/assets/66907547/e2570e88-a5d8-4946-ab77-ec8221b6656c)
我已经实现了对应的方法
![image](https://github.com/moztl/Free-Mybatis-Tool/assets/66907547/071e9725-f808-4b81-a170-8a3e65b547bf)
点击方法前面的Mapper类是可以跳转到对应的类的
![image](https://github.com/moztl/Free-Mybatis-Tool/assets/66907547/a56a6e20-6357-4f77-b55a-757022fd380c)
请问作者是否有计划实现点击select中的方法也可以跳转到对应方法的功能，或者是已经实现了但是我什么地方没配置对导致的。谢谢！

**Comment by moztl** [comment]
感谢反馈，插件暂未涉及 association 当中 select 的快速跳转功能，现有的跳转功能是默认功能（仅支持跳转到类）。您所提出的是个很好的功能优化点，插件会考虑加入该功能。
